Add empty featuresets for armel to help abiupdate script
The abiupdate script bails out currently (since we disabled armel image
builds at least temporarily) with

	Retrieve config
	Traceback (most recent call last):
	  File "debian/bin/abiupdate.py", line 224, in <module>
	    Main(url, url_config, **kw)()
	  File "debian/bin/abiupdate.py", line 95, in __call__
	    self.update_arch(config, arch)
	  File "debian/bin/abiupdate.py", line 149, in update_arch
	    featuresets = config[('base', arch)]['featuresets']
	KeyError: 'featuresets'

Possibly this should be handled more gracefully in abiupdate itself, but
workaround the situation first by adding an empty featuressets and
explaining in the comment why we do not build images.

In the long run armel will disapear completely.

Gbp-Dch: Ignore